### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by Entkenntnis** [BaumianerNiklas/quicalc#1]
Hi Niklas, nice project :100: looks clean.

congrats for reaching 1061 points on https://hack.arrrg.de/ :grinning:

**Comment by BaumianerNiklas** [comment]
Thank you! I really enjoyed doing the challenges and I appreciate you reaching out to me :D 

(I'm closing this issue because it doesn't really relate to the project but feel free to comment further if you have anything more to say!)

**Comment by Entkenntnis** [comment]
Ich wechsle kurz auf deutsch :) Hättest du Lust, mir ein wenig zu erzählen, wie es dir bei der Bearbeitung der Aufgaben auf Hack The Web gegangen ist? Also z.B. welche Aufgaben dir besonders gut gefallen haben, welche eher schwierig waren oder wo du einen besonderen Lösungsweg gefunden hast? Solches Feedback ist für mich sehr wertvoll und hilft mir z.B. beim Entwickeln neuer Aufgaben xD falls du Ideen für Aufgaben hast, dann auch gerne!

Wenn du magst kann du auf meine E-mail schreiben hack@arrrg.de

**Comment by BaumianerNiklas** [comment]
Gerne doch :D 
Erstmal sollte ich vielleicht sagen, dass ich nicht alle Aufgaben von allein gelöst habe und vor allem bei den letzteren (wie z.B. Sag Mal) auch mit einigen Freunden zusammen daran gearbeitet habe (das sind jetz mehr oder weniger auch die restlichen Spieler, die auf Platz 1 sind)

Ich versuche mal hier die Aufgaben in kleine Kategorien einzuteilen, die ich besonders spaßig zu lösen fand:
- Aufgaben bei denen man Funktionen seines Browsers nutzen musste bzw. Einstellungen ändern musste (zB Ausdruck, Hell und Dunkel, NoScript). Die waren zwar meistens ziemlich simpel aber zum lösen trotzdem nett
- Aufgaben bei denen man ein bisschen im Quellcode/ JavaSkript-Dateien "rumschnuppern" musste und eventuell dementsprechend dann auch eigene passende Befehle in der Konsole eingeben musste (zB Ladebalken 1/2, Cheater, Spielstand 1). Das waren auch oft Aufgaben, bei denen es eine offensichtliche aber unbrauchbare Lösung gibt (wie einfach warten), was sich finde ich einfach immer gut angefühlt hat zu lösen (weiteres Beispiel hierfür wäre evtl Verlosung)
- Aufgaben, bei denen man etwas "Tech-Wissen" mitbringen musste oder sich vielleicht ein eigenes kleines Skript oder so schreiben musste (zB Datei X, Sag Mal, Kopfdaten, Blockchain, ...)
- Aufgaben, denen ich jetzt keine wirkliche Kategorie zuordnen kann, die ich aber einfach kreativ und lustig zu lösen fand sind zB Matrix, die Taschenrechner, Terminal, und Labyrinth :')

Generell waren aber keine Aufgaben dabei, bei denen ich sagen würde, dass sie nicht Spaß gemacht haben zu lösen. Vor allem die Aufgaben nach "Finale" waren meiner Meinung nach wirklich interessant :D

Mir fallen gerade 3 Aufgaben ein, die ich wahrscheinlich nicht nach dem vorgesehen Weg gelöst habe:
- Cheater: Hier hab ich ganz unten im Skript `bloby.js` "Die Antwort lautet" und dann unzählige Klammern und sonstige Symbole gefunden. Ich hatte schon mal von [jsfuck](https://jsfuck.com) gehört und hab mir halt gedacht, dass man dieses Klammerzeug wahrscheinlich einfach in einer JS-Umgebung ausführen kann, was dann halt auch geklappt hat :D
- Geheimtext: Auf der Website wurde schon öfters "Die Antwort lautet" verwendet, und ich hab halt gemerkt, dass sich das auch hier auf die letzten paar Wörter von den Buchstaben her genau ausgehen würde, was halt schon einige Buchstaben "entschlüsselt" hat. Danach war es im Endeffekt nur noch raten.
- POST It: Ich bin mir nicht sicher, ob die Lösung hier die richtige is oder nich. Ich hab ewig versucht mit cURL die POST request der Input Felder nachzuahmen, was aber nicht geklappt hat. Nach einiger Zeit sind wir dann (mehr oder weniger auch aus Spaß) darauf gekommen, dass man sich ja "seinen eigenen Input bauen" könnte und einfach den Code einer vorherigen Aufgabe reinpasten, was dann auch funktioniert hat. 

Zu Cheater hab ich mittlerweile die wahrscheinlich vorgesehen Lösung gefunden, zu Geheimtext aber ehrlich gesagt noch nicht. Einige Aufgaben, vor allem die späteren, haben mir insofern Schwierigkeiten gemacht, dass sie schon schwer waren zu lösen, aber ich würde bei keiner Aufgabe jetzt sagen, dass sie so schwer war, dass sie keinen Spaß gemacht hat/ nervig oder so war. (Vielleicht ist mein Blickwinkel hier aber auch ein bisschen verzerrt, wir haben ja wie gesagt auch an einigen Aufgaben zusammengearbeitet)

Hoffe ich konnte dir damit weiterhelfen, ich würde mich definitiv über weiteren Content freuen! :))

**Comment by Entkenntnis** [comment]
Vielen Dank für diesen ausführlichen Bericht! Schön zu hören, dass ihr das als Gruppe angegangen seid - häufig sind Hacker ja eher Einzelkämpfer ;) aber zusammen hat man definitiv mehr "brain power" und findet auch mehr Ideen. Deine Lösungswege zu Cheater, Geheimtext und POST It sind ziemlich clever - damit hast du quasi die Hacking-Aufgabe "gehackt" (it's getting meta). Bei POST it muss man bei cURL noch auf das Session-Cookie achten, daran hat es wahrscheinlich gelegen. Für Geheimtext gibt es sogar ein ziemlich bekanntes (quasi automatisches) Standardverfahren.

Respekt habe ich, dass ihr euch an Sag mal rangewagt habt, hätte nicht erwartet, dass in absehbarer Zeit jemand diese Aufgabe löst :)

Einen festen Zeitplan gibt es nicht, aber es wird in der nächsten Zeit sicher neuen Content geben.
